[Export]
baked_state = false
baked_notebookfile = false
offer_binder = true
slider_server_url= "https://mriqc-demo.netlify.app/"
enabled = true
output_dir = "www"
create_index = true


[SliderServer]
port = 80
host = "0.0.0.0"
