[Export]
baked_state = false
baked_notebookfile = false
enabled = true
create_index = true
output_dir = "www"
slider_server_url = "https://mriqc-demo.netlify.app"
ignore_cache = [
    "index.jl",
]

[SliderServer]
